// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOB400aXBA2hH6vKTozOl3w_YVaLiAjDo',
    appId: '1:298673013461:web:173c4708fceae21e9a185c',
    messagingSenderId: '298673013461',
    projectId: 'manakrishiapp',
    authDomain: 'manakrishiapp.firebaseapp.com',
    storageBucket: 'manakrishiapp.firebasestorage.app',
    measurementId: 'G-QF5557JK6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjaKXM9T2FJ4eTtO852DtREpDP3fFNZBM',
    appId: '1:298673013461:android:09e37c08ec33b3729a185c',
    messagingSenderId: '298673013461',
    projectId: 'manakrishiapp',
    storageBucket: 'manakrishiapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJSRwExuBQpKi1WhaFivOI_PL8XylU8xg',
    appId: '1:298673013461:ios:3d64febb5481e93f9a185c',
    messagingSenderId: '298673013461',
    projectId: 'manakrishiapp',
    storageBucket: 'manakrishiapp.firebasestorage.app',
    iosBundleId: 'com.manakrishi.manakrishiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJSRwExuBQpKi1WhaFivOI_PL8XylU8xg',
    appId: '1:298673013461:ios:3d64febb5481e93f9a185c',
    messagingSenderId: '298673013461',
    projectId: 'manakrishiapp',
    storageBucket: 'manakrishiapp.firebasestorage.app',
    iosBundleId: 'com.manakrishi.manakrishiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOB400aXBA2hH6vKTozOl3w_YVaLiAjDo',
    appId: '1:298673013461:web:a0f448cbbc1c97aa9a185c',
    messagingSenderId: '298673013461',
    projectId: 'manakrishiapp',
    authDomain: 'manakrishiapp.firebaseapp.com',
    storageBucket: 'manakrishiapp.firebasestorage.app',
    measurementId: 'G-DTL2TJYM46',
  );
}
